first_project/first_app/urls.py
from django.urls import path
from . import views

app_name = "first_app"


urlpatterns = [
    path('', views.index , name='index'),
    path("weather/",views.weather_view,name="weatherview")
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('first_app/', include('first_app.urls')),
    path('admin/', admin.site.urls),
]

first_project/first_app/models.py
from django.db import models

# Create your models here.

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse

# Create your views here.

def index(request):
    return render(request,"first_app/first.html")

def weather_view(request):
    weather_dictionary = {
        "istanbul" : "30", 
        "amsterdam" : "20",
        "paris" : [5,14,20,21],
        "rome" : {"morning" : 10, "evening" : 20},
        "user_premium" : True,
        "test" : "Test test Test test"
        }
    return render(request,"first_app/weather.html",context=weather_dictionary)

first_project/first_app/templates/first_app/first.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>test test</h1>
<img src="{% static 'first_app/metallica.jpg' %}" alt="metallica">
{% endblock %}

first_project/first_app/templates/first_app/weather.html
{% extends 'base.html' %}

{% block content %}
    <h1>Weather Report</h1>
    <br>
    <!-- jinja syntax -->
    <h2>Istanbul: {{istanbul}}</h2>
    <br>
    <h2>Amsterdam: {{amsterdam}}</h2>
    <br>
    <ul>
    {% for key,value in rome.items %}
        <h2><li>Rome: {{key}} : {{value}}</li></h2>
    {% endfor %}
    </ul>
    <br>
    
    {% if user_premium %}
        <ul>
        {% for item in paris %}
            {% if item < 6 %}
                <h2><li>Paris: Too Cold</li></h2>
            {%else%}
                <h2><li>Paris: {{item}}</li></h2>
            {% endif %}
        {% endfor %}
        </ul>
    {% endif %}

    <br>
    
    <h2>{{test | lower}}</h2>

    <br>

    <!--<h2><a href="{% url 'first_app:index' %}">Go to Index</a></h2>-->

    {% endblock %}

first_project/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <title>My Main Website</title>

    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
  
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
  
        .b-example-divider {
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }
  
        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }
  
        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }
  
        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }
  
        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }
        body {
            min-height: 75rem;
            padding-top: 4.5rem;
        }
      </style>
  
</head>
<body>
    
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Weather App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'first_app:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'first_app:weatherview' %}">Weather Report</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

{% block content %}

{% endblock %}

<h1>END OF BASE HTML</h1>
</body>
</html>